[workspace]
members = ["labelswap-data"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.86"
thiserror = "1.0.61"
