[package]
name = "labelswap-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
image = "0.25.1"
serde_json = "1.0.120"
thiserror.workspace = true
